#ifndef ASEMANTOOLS_GLOBAL_H
#define ASEMANTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBASEMANTOOLS_LIBRARY)
#  define LIBASEMANTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBASEMANTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ASEMANTOOLS_GLOBAL_H
