#! /bin/sh 

RUN_FILE=`readlink "$0"`
if [ "${RUN_FILE}" = "" ]; then
    RUN_FILE="$0"
fi
if [ "${ASEMAN_DATA_PATH}" = "" ]; then
    ASEMAN_DATA_PATH="`echo $RUN_FILE | grep ^/`"
    if [ "$ASEMAN_DATA_PATH" = "" ]; then
	ASEMAN_DATA_PATH="$PWD"/"$RUN_FILE"
    fi
    DIR="$PWD"
    DIR_NAME=`dirname "$ASEMAN_DATA_PATH"`
    cd "$DIR_NAME"
    ASEMAN_DATA_PATH="$PWD"
fi

export QT_QUICK_CONTROLS_STYLE=material
qmlscene "$ASEMAN_DATA_PATH/main.qml" "$@"
